#ifndef PDLBRD_KEYS_H
#define PDLBRD_KEYS_H

#define NB_PIN 8

typedef enum
{
	PDLBRD_NO_SEG = -1,
	PDLBRD_SEG_1,
	PDLBRD_SEG_2,
	PDLBRD_SEG_3,
	PDLBRD_SEG_4,
	PDLBRD_NB_SEG
} pdlbrd_seg_t;

typedef enum
{
	PDLBRD_KEY_C1,
	PDLBRD_KEY_CS1,
	PDLBRD_KEY_D1,
	PDLBRD_KEY_DS1,
	PDLBRD_KEY_E1,
	PDLBRD_KEY_F1,
	PDLBRD_KEY_FS1,
	PDLBRD_KEY_G1,
	PDLBRD_KEY_GS1,
	PDLBRD_KEY_A1,
	PDLBRD_KEY_AS1,
	PDLBRD_KEY_B1,
	PDLBRD_KEY_C2,
	PDLBRD_KEY_CS2,
	PDLBRD_KEY_D2,
	PDLBRD_KEY_DS2,
	PDLBRD_KEY_E2,
	PDLBRD_KEY_F2,
	PDLBRD_KEY_FS2,
	PDLBRD_KEY_G2,
	PDLBRD_KEY_GS2,
	PDLBRD_KEY_A2,
	PDLBRD_KEY_AS2,
	PDLBRD_KEY_B2,
	PDLBRD_KEY_C3,
	PDLBRD_KEY_CS3,
	PDLBRD_KEY_D3,
	PDLBRD_NO_KEY_PRESSED,
	PDLBRD_NB_KEYS,
} pdlbrd_key_t;

extern const char* PDLBRD_KEY_STR[PDLBRD_NB_KEYS];
extern const pdlbrd_key_t PDLBRD_KEY_MAP[PDLBRD_NB_SEG][NB_PIN];
#endif // PDLBRD_KEYS_H
